### ISSUE TITLE
Decompressed

### ISSUE THREAD

**Issue by Larissa-11** [mx54039q/entroformer#10]
我在解压缩的照片的时候遇到了：RuntimeError: "min_all" not implemented for 'Half'

**Comment by mx54039q** [comment]
我已收到你的邮件。                                               by    钱一琛

**Comment by mx54039q** [comment]
这个问题我没有遇到过, 你能再描述详细一点吗?

**Comment by Larissa-11** [comment]
![4e0285739e4a4872e0f20b60686d3a0](https://user-images.githubusercontent.com/63986093/205839456-43e87659-56d5-4957-af60-85719ea42305.png)
这是报错时的截图

**Comment by mx54039q** [comment]
我猜测这里可能是你使用的pytorch版本下半精度没有min()和max()实现.
你可以注释掉compress代码和decompress代码中的半精度推理部分, 该操作只是防止在输入大分辨率图时可能产生的OOM内存溢出.
