### ISSUE TITLE
为什么用不同的预训练模型，得到的二进制文件的大小都是一样的

### ISSUE THREAD

**Issue by Larissa-11** [mx54039q/entroformer#11]
为什么用不同的预训练模型，得到的二进制文件的大小都是一样的，而且二进制的文件比图像的大小还大，怎么体现了压缩呢

**Comment by mx54039q** [comment]
1. 第一个问题你能否再描述详细一些.
2. 我们的方式是有损图像压缩. 原始图像的存储方式可能是无损的(比如PNG), 也可能是有损的 (比如JPG). 压缩体现的是和无损的原始数据相比的.

**Comment by Larissa-11** [comment]
![模型](https://user-images.githubusercontent.com/63986093/205839973-08369bf3-1d8a-4391-8dd4-8477c12c008c.png)
利用您训练好的三种预训练模型，lambad不同会有不同的码率，不同的码率在压缩图片的时候，得到的压缩文件不应该不一样大小吗？ 我去压缩一张几百KB的照片，得到的压缩文件是1.2M，这样看来并没有起到压缩的作用。您说压缩体现的是和无损的原始数据相对比的，我不太明白这样的意义是啥？ 在电脑中有一张几百KB的JPG格式的照片，用您的压缩模型对其进行压缩，压缩以后的得到的二进制文件是1.2M，反而占用电脑存储更大的空间了。

**Comment by mx54039q** [comment]
1. 你这里显示的是模型文件, 不同的预训练模型有同样大小的参数, 所以他们的模型文件大小是一样的.
2. 首先你可能需要理解一下压缩率的含义 bpp (bits per pixel) = bits / pixels. 另外, JPG本身就是一种图像压缩算法, 你电脑中的JPG格式的照片是已经压缩后的文件, 你在一个已经被压缩的图片上再使用压缩算法, 是无法得到进一步的压缩效果的. 并且, 你不能仅仅看压缩率, 还需要看图像的恢复程度 (也就是distortion). 我建议你找一张无损格式的图像, 然后用我们的算法和JPG进行比较.
