### ISSUE TITLE
torchac 中的BitInputStream类

### ISSUE THREAD

**Issue by Echo-cwb** [mx54039q/entroformer#12]
您好，我想问一下BitInputStream类要怎么使用呀，我想得到bin文件的纯0,1bit流数据

**Comment by mx54039q** [comment]
我已收到你的邮件。                                               by    钱一琛

**Comment by Echo-cwb** [comment]
抱歉我理解错了，我想问一下.bin文件要如何得到纯0,1bit的数据呢，我打开的话都是乱码，另外我想问一下如果.bin文件中有部分bytes错了，模型还能够解码吗

**Comment by mx54039q** [comment]
1. bin文件直接用  open('file', 'rb') as f: f.read() 这样读取就可以得到bit数据流. 
2. 如果bytes错误, 不能解码.
