### ISSUE TITLE
Inquiry: Extending Model Capability for High Resolution Image Compression

### ISSUE THREAD

**Issue by sonainjameel** [mx54039q/entroformer#17]
Hi,

I've been experimenting with your model and found it to be quite effective for compressing low-resolution images. However, I've encountered some challenges when attempting to compress high-resolution images such as test images of JPEG AI, where the model seems to underperform or fail.

Could you provide any insights or recommendations on how to adapt or extend the model to handle high-resolution image compression more effectively? Are there specific parameters or modifications that can be made to accommodate larger image sizes?

I appreciate your work on this project and any guidance you can offer on this matter.

Thank you!

**Comment by mx54039q** [comment]
Our models are pretrained on 256x256 images and then trained on 384x384 images, which probably is the reason for the performance on high-resolution images. My recommendation is to expand the size of the images.

**Comment by sonainjameel** [comment]
Thanks, I will try and if I face any issue, I will let you know.
