### ISSUE TITLE
Checkpoint for psnr = 37.72

### ISSUE THREAD

**Issue by makinyilmaz** [mx54039q/entroformer#8]
Dear author,

Thank you for your precious work ! I am experimenting with your code and could not find the pertained model producing 37.72 dB on Kodak dataset. Is it possible to share the checkpoint for that quality? In addition, if you have parallel entroformer checkpoints for higher lambdas, is it possible to share them as well ?

Thanks in advance

**Comment by mx54039q** [comment]
Hi, thanks for your interest in our work.

I'm sorry that I forgot to upload the pretrained model with 37.72 PSNR on Kodak dataset. The model has been uploaded to google drive. 

We only trained the parallel entroformer for low bpps.

**Comment by makinyilmaz** [comment]
Thanks a lot for your response and help. Wish you the best

**Comment by mx54039q** [comment]
我已收到你的邮件。                                               by    钱一琛
