### ISSUE TITLE
训练集的获取与图片选择

### ISSUE THREAD

**Issue by hzyBupt** [mx54039q/entroformer#9]
您好，感谢您的工作与开源。
我想要用compressai重新复现您的工作，但我的数据集存在尺寸不足384的图片，并且复现结果和数据集存在相关性。在论文中提到数据集的选择是：“We choose 14886 images from OpenImage (Krasin et al., 2017) as our training data.”。OpenImage好像有很多版本 ，并且图片数量十分庞大。
**请问您是如何选择图片以保证数据集中的多样性？此外，不知您是否方便上传您的数据集？**
希望收到您的回复，谢谢！

**Comment by mx54039q** [comment]
你好, 前一阵子比较忙, 没来得及回复, 抱歉.
对于有损图像压缩任务, 训练集数据量的增加, 其实对于性能的提升并不大了. 我使用OpenImage的时候, 也只是简单地过滤了尺寸不足的图片, 然后将过大尺寸的图片进行缩小.

**Comment by MeycL** [comment]
Thank you for the open source of your work. I am very eager to get the training set data you describe in your paper, could you publish or send a separate copy if convenient?

**Comment by mx54039q** [comment]
我已收到你的邮件。                                               by    钱一琛
